# Site settings
title: "porfolio"
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://Kimmingyunim.github.io" # the base hostname & protocol for your site

# User setting
owner:  "Kim mingyu"
email:  "looaool@nate.com"
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:  "010-4299-4321"
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
